# Generated by Django 3.2.4 on 2021-06-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number 2 (Optional)'),
        ),
    ]
