# Generated by Django 3.2.4 on 2021-07-02 14:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_phone_phone_number_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(default="Anonymus", max_length=50),
        ),
    ]
