# Generated by Django 3.2.4 on 2021-07-08 10:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20210702_2210"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_address_deleted",
            field=models.BooleanField(
                default=False, verbose_name="To delete address check this box, don't click the delete button"
            ),
        ),
    ]
