name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run:
        name: set SECRET_KEY
        command: |
          SECRET_KEY="django-insecure-z!@8xvitr3imfo6yh(#i#+kww)-3&#5aa#6bme9e_hcy10(@xm"
          echo SECRET_KEY
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: python manage.py test