# Generated by Django 3.2.4 on 2021-06-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('TV', 'TV'), ('Laptop', 'Laptop'), ('Computer', 'Computer'), ('Electronic', 'Electronic'), ('Other', 'Other')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
