# Generated by Django 3.2.4 on 2021-06-13 06:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210613_1042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.JSONField(),
        ),
    ]
